OstiaHouse6Floor2_MapScripts::
	.byte 0


OstiaDollGirl::
# 4 "data/maps/OstiaHouse6Floor2/scripts.pory"
	lock
# 5 "data/maps/OstiaHouse6Floor2/scripts.pory"
	faceplayer
# 6 "data/maps/OstiaHouse6Floor2/scripts.pory"
	msgbox OstiaDollGirl_Text_0
# 9 "data/maps/OstiaHouse6Floor2/scripts.pory"
	release
	return


OstiaDollGirl_Text_0:
# 6 "data/maps/OstiaHouse6Floor2/scripts.pory"
	.string "I like to hide in all my plush pokémon.\n"
	.string "My brother has a hard time finding me\l"
	.string "when I do though.$"
