OstiaResearchInstituteFloor2_MapScripts::
	.byte 0


OstiaResearchTableScientist1::
# 4 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	lock
# 5 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	msgbox OstiaResearchTableScientist1_Text_0
# 7 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	release
	return


OstiaResearchTableScientist2::
# 11 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	lock
# 12 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	msgbox OstiaResearchTableScientist2_Text_0
# 15 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	release
	return


OstiaResearchTableScientist3::
# 19 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	lock
# 20 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	faceplayer
# 21 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	msgbox OstiaResearchTableScientist3_Text_0
# 25 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	release
	return


OstiaResearchDeskScientist1::
# 29 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	lock
# 30 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	faceplayer
# 31 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	msgbox OstiaResearchDeskScientist1_Text_0
# 35 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	release
	return


OstiaResearchDeskScientist2::
# 39 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	lock
# 40 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	faceplayer
# 41 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	msgbox OstiaResearchDeskScientist2_Text_0
# 47 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	release
	return


OstiaResearchDeskScientist3::
# 51 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	lock
# 52 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	faceplayer
# 53 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	msgbox OstiaResearchDeskScientist3_Text_0
# 63 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	release
	return


OstiaResearchTableScientist1_Text_0:
# 5 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	.string "What if we tried quantum compression to\n"
	.string "bring more fuel?$"

OstiaResearchTableScientist2_Text_0:
# 12 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	.string "No, I don't think that would work.\n"
	.string "The particle compiler would take up too\l"
	.string "much space.$"

OstiaResearchTableScientist3_Text_0:
# 21 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	.string "I'm drafting blueprints for a top secret\n"
	.string "project.\p"
	.string "Because it's a secret, I can't tell you\n"
	.string "any more about it.$"

OstiaResearchDeskScientist1_Text_0:
# 31 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	.string "We've been doing a lot of work to extract\n"
	.string "DNA from fossils.\p"
	.string "So far, the only pokémon we've been able\n"
	.string "to get a sample from is Shellos.$"

OstiaResearchDeskScientist2_Text_0:
# 41 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	.string "I'm trying to figure out what ancient\n"
	.string "pokémon ate and which environments\l"
	.string "they may have lived in.\p"
	.string "There's a lot that we can learn from the\n"
	.string "shapes of their fossils and the areas\l"
	.string "in which they were found.$"

OstiaResearchDeskScientist3_Text_0:
# 53 "data/maps/OstiaResearchInstituteFloor2/scripts.pory"
	.string "Recently, we've discovred some evidence\n"
	.string "of a strange pokémon from the past.\p"
	.string "Many of the prehistorical pokémon we've\n"
	.string "documented had similar qualities, but\l"
	.string "the pokémon that these fossils depict\l"
	.string "share little resemblance to others.\p"
	.string "We think they have a hard stone-like\n"
	.string "shell hiding a luminous colored body\l"
	.string "beneath.\p"
	.string "Strange, isn't it?$"
